# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e80e0e913ec878e7ddd33455e01fb1d249d677d0e89438b5a2ac840036de9816f803f416115b2eb5086caec1f3a78fb516c6949226912a2aa0a0163c1cac7f

test:
  secret_key_base: f0c25e8ca551083375bda27ffd4de142914414122e6d74a1672e74af140ae473ada6b4284064af51115855665a0a0920d5ea7825d419e4c663aecb02f0b40604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
